### PR TITLE
Fix default hot-key configuration

### PR DESCRIPTION
**Pull request by vkareh**
@ikeydoherty - here's a quick pull request to fix the default keybinding. Let me know if this one works for you.

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Let's try it out :)

**Comment by ikeydoherty** [comment]
Yeah turns out I'm just a muppet. Confirmed this is working, thank you!

**Comment by vkareh** [comment]
haha, good thing I checked ;)
thanks for merging!

**Comment by ikeydoherty** [comment]
Pfft - thanks for writing :P

**Pull request merged**
